name: Deploy Backend to Hugging Face
on:
  push:
    branches: [main]
    paths:
      - 'veriscan-backend/**'
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: pip install huggingface_hub
      - name: Push to Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python -c 'import os; from huggingface_hub import HfApi; api = HfApi(token=os.environ.get("HF_TOKEN")); api.upload_folder(folder_path="./veriscan-backend", repo_id="Shoumik1908/veriscan-backend", repo_type="space", ignore_patterns=["models/*.h5", ".git/*", "__pycache__/*"])'
